epoll.lo: /home/chopin/bin/toknot/epoll/epoll.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/chopin/bin/toknot/epoll $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/chopin/bin/toknot/epoll/epoll.c -o epoll.lo 
$(phplibdir)/epoll.la: ./epoll.la
	$(LIBTOOL) --mode=install cp ./epoll.la $(phplibdir)

./epoll.la: $(shared_objects_epoll) $(EPOLL_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_epoll) $(EPOLL_SHARED_LIBADD)

